version: '1'

services:
  python_occ:
    restart: always
    container_name: pythonOCC_Application
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
       PORT: 5000